### ISSUE TITLE
Unable to get this configured

### ISSUE THREAD

**Issue by thrillerxx** [KayLerch/alexa-flashbriefing-soundcloud-gateway#1]
![snip20171112_2](https://user-images.githubusercontent.com/33615693/32711206-7233fa6e-c803-11e7-88f6-08df09a7d8d7.png)

Sorry I am new to Github. But I am having issues getting a https address. 

![snip20171112_1](https://user-images.githubusercontent.com/33615693/32711200-6a167640-c803-11e7-869d-0291b7d8a72e.png)

**Comment by thrillerxx** [comment]
any help or link would be of great assistance.

Thank you for creating this btw

**Comment by asibirtseva** [comment]
Got this working after replacing below line in handler.js :
 
module.exports.feed = (event, context, callback)
with:
module.exports.handler = (event, context, callback)

**Comment by KayLerch** [comment]
Sorry for not coming back any sooner. Great, you fixed it on your own.

Did you use serverless deploy to roll out the stack? Instead of changing the code you could also change the handler reference in the Lambda console to "handler.feed". This should automatically be done when using serverless as serverless.yml has this setting (see https://github.com/KayLerch/alexa-flashbriefing-soundcloud-gateway/blob/master/serverless.yml#L15)
